In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)

In [3]:
x

tensor([[0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.1704e-41, 0.0000e+00, 2.2369e+08],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [4]:
y = torch.rand(5, 3)
y

tensor([[0.4469, 0.0462, 0.1002],
        [0.1236, 0.3017, 0.7719],
        [0.0858, 0.5182, 0.3429],
        [0.6170, 0.7803, 0.0239],
        [0.5040, 0.0704, 0.7735]])

In [6]:
x.size()

torch.Size([5, 3])

In [7]:
x = torch.randn(4, 4)

In [8]:
x

tensor([[ 0.7046, -1.0265,  0.3847,  0.5612],
        [ 1.2403, -0.9116,  0.3265,  1.2251],
        [ 1.1607, -0.0821, -1.1332,  1.2597],
        [ 0.4337,  0.0062,  0.7098,  0.6450]])

In [9]:
x.view(16)

tensor([ 0.7046, -1.0265,  0.3847,  0.5612,  1.2403, -0.9116,  0.3265,  1.2251,
         1.1607, -0.0821, -1.1332,  1.2597,  0.4337,  0.0062,  0.7098,  0.6450])

In [15]:
x.view(-1, 2)

tensor([[ 0.7046, -1.0265],
        [ 0.3847,  0.5612],
        [ 1.2403, -0.9116],
        [ 0.3265,  1.2251],
        [ 1.1607, -0.0821],
        [-1.1332,  1.2597],
        [ 0.4337,  0.0062],
        [ 0.7098,  0.6450]])

In [16]:
x.view(-1, 8)

tensor([[ 0.7046, -1.0265,  0.3847,  0.5612,  1.2403, -0.9116,  0.3265,  1.2251],
        [ 1.1607, -0.0821, -1.1332,  1.2597,  0.4337,  0.0062,  0.7098,  0.6450]])

In [17]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [21]:
torch.cuda.is_available()

False